// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePostgresSslMode } from "./src/lib/databaseUrl";

const previewMigrateUrl =
  process.env.VERCEL_ENV?.trim() === "preview"
    ? process.env.PREVIEW_DATABASE_URL?.trim()
    : undefined;

const rawMigrateUrl =
  previewMigrateUrl ??
  process.env.POSTGRES_URL_NON_POOLING?.trim() ??
  process.env.DATABASE_URL?.trim() ??
  process.env.POSTGRES_PRISMA_URL?.trim();

const migrateUrl = normalizePostgresSslMode(rawMigrateUrl);

if (!migrateUrl) {
  throw new Error(
    "Missing PREVIEW_DATABASE_URL (for Vercel Preview), POSTGRES_URL_NON_POOLING, DATABASE_URL, or POSTGRES_PRISMA_URL.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl,
  },
});
