// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {
  normalizePostgresSslMode,
  selectMigrationDatabaseUrl,
} from "./src/lib/databaseUrl";

const rawMigrateUrl = selectMigrationDatabaseUrl(process.env);
const migrateUrl = normalizePostgresSslMode(rawMigrateUrl);

if (!migrateUrl) {
  throw new Error(
    "Missing PREVIEW_DATABASE_URL (for Vercel Preview), POSTGRES_URL_NON_POOLING, DATABASE_URL, or POSTGRES_PRISMA_URL.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl,
  },
});
