CREATE TABLE "ItqResult" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "eventDescription" TEXT,
    "eventTiming" TEXT NOT NULL,
    "ptsdScore" INTEGER NOT NULL,
    "dsoScore" INTEGER NOT NULL,
    "reScore" INTEGER NOT NULL,
    "avScore" INTEGER NOT NULL,
    "thScore" INTEGER NOT NULL,
    "adScore" INTEGER NOT NULL,
    "nscScore" INTEGER NOT NULL,
    "drScore" INTEGER NOT NULL,
    "ptsdFunctional" BOOLEAN NOT NULL,
    "dsoFunctional" BOOLEAN NOT NULL,
    "ptsdMet" BOOLEAN NOT NULL,
    "dsoMet" BOOLEAN NOT NULL,
    "resultLabel" TEXT NOT NULL,
    "p1" INTEGER NOT NULL,
    "p2" INTEGER NOT NULL,
    "p3" INTEGER NOT NULL,
    "p4" INTEGER NOT NULL,
    "p5" INTEGER NOT NULL,
    "p6" INTEGER NOT NULL,
    "p7" INTEGER NOT NULL,
    "p8" INTEGER NOT NULL,
    "p9" INTEGER NOT NULL,
    "c1" INTEGER NOT NULL,
    "c2" INTEGER NOT NULL,
    "c3" INTEGER NOT NULL,
    "c4" INTEGER NOT NULL,
    "c5" INTEGER NOT NULL,
    "c6" INTEGER NOT NULL,
    "c7" INTEGER NOT NULL,
    "c8" INTEGER NOT NULL,
    "c9" INTEGER NOT NULL,

    CONSTRAINT "ItqResult_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "ItqResult" ADD CONSTRAINT "ItqResult_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
