import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import RightSection from "@/components/layout/RightSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <div className="flex justify-center min-h-screen max-w-[1265px] mx-auto">
          <Sidebar />
          <main className="flex-1 min-w-0 border-r border-zinc-800 lg:border-r-0 lg:border-x min-h-screen">
            {children}
          </main>
          <RightSection />
        </div>
      </body>
    </html>
  );
}
